FROM node:latest

WORKDIR /app

#COPY package.json package-lock.json ./

COPY ./backend ./backend
COPY ./common-types ./common-types

WORKDIR /app/common-types

RUN npm install

WORKDIR /app/backend

RUN npm install

EXPOSE 5000

#CMD ["/bin/bash"]
CMD ["npm", "start"]