services:
  mysqldb:
    build:
      context: ../mysql-gettext
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ../mysql-gettext/db/backup/files/:/data_backup/data
      - ../mysql-gettext/db/init-scripts:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysqldb
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysqldb

volumes:
  db-config:
  db-data:
